export const metrics = [
  ['121', 'Newcomer entrepreneurs supported', 'Across 3 cohorts within 1 year'],
  ['400+', 'Hours of 1-to-1 mentorship delivered', 'High-touch guidance across key business decisions'],
  ['110', 'Workshops and training sessions', 'Across all cohorts, including 30 in Cohort 3'],
  ['10', 'Networking events', 'Connecting founders with the local ecosystem and business community'],
  ['200+', 'Hours of 1-to-1 settlement support delivered', 'Business progress paired with integration support'],
  ['140', 'Family members supported', 'Extending impact beyond the founder alone'],
].map(([value, label, detail]) => ({ value, label, detail }));

export const bramptonImpacts = [
  'Activating high-potential newcomer talent that might otherwise remain underutilized',
  'Helping founders establish businesses and long-term roots in Brampton',
  'Strengthening the local innovation ecosystem through participation and connection',
  'Contributing to long-term economic growth and community development',
];

export const founderStories = [
  {
    id: 'enabled-talent',
    company: 'Enabled Talent',
    name: 'Amandeep Singh',
    photo: 'FounderPics/Enable_Talent_Amandipp.png',
    then: 'Founder struggling with communication and scale',
    now: 'now has 20,000 users + international partnerships',
    fullThen: 'Entered the program before revenue and operations, while struggling to communicate his vision confidently.',
    fullNow: 'Enabled Talent reached over 20,000 users, expanded internationally, built partnerships, and earned major recognition.',
  },
  {
    id: 'aishar',
    company: 'AISHAR',
    name: 'Manmeet Singh',
    photo: 'FounderPics/AISHAR_Manmeet_Singh.png',
    then: 'Experienced technologist entering a new market',
    now: 'grew from $60K to $500K in secured contracts within 14 weeks',
    fullThen: 'After years at major Silicon Valley companies, Manmeet needed a Canadian go-to-market and procurement playbook.',
    fullNow: 'AISHAR defined customer personas, built a stronger market strategy, and secured $500,000 in contracts.',
  },
  {
    id: 'dacasto',
    company: 'Dacasto',
    name: 'Enrico & Laura Dacasto',
    photo: 'FounderPics/DacastoGranPasticceria_Enrico_Dacasto.png',
    then: 'Italian family bakery entering Canadian market',
    now: 'now have 2 stores, 25 employees, $1.3M revenue',
    fullThen: 'The Dacastos arrived from Italy with deep baking expertise but needed support with incorporation, regulations, settlement, and market entry.',
    fullNow: 'Dacasto now operates two stores, employs 25 people, generates $1.3M in revenue, and is expanding further.',
  },
  {
    id: 'bookmytherapy',
    company: 'BookMyTherapy',
    name: 'Neha Juwale',
    photo: 'FounderPics/BookMyTherapy_Neha_Juwale.jpg',
    then: 'Founder cautious about partnerships and idea sharing',
    now: 'secured community partnerships and public recognition',
    fullThen: 'Neha was building a mental-health access platform but struggled with partnership risk and confidence in sharing the idea.',
    fullNow: 'She secured community collaborations, pitched publicly, and earned recognition for her contribution to mental health.',
  },
  {
    id: 'questify',
    company: 'Questify',
    name: 'Vynavin Vinod & Madheswaran Kamal',
    photo: 'FounderPics/Questify_Vynanvin_Madheswaran.png',
    then: 'Student founders with an AI learning idea',
    now: 'named among Canada top EdTech companies',
    fullThen: 'Two high school founders entered with an MVP-stage idea but no business infrastructure, pilot strategy, or investor narrative.',
    fullNow: 'Questify launched a school-board pilot, won startup recognition, and advanced toward product launch.',
  },
  {
    id: 'silknext',
    company: 'SilkNext',
    name: 'Chhavi Dikholkar',
    photo: 'FounderPics/SilkNext_Chhavi_Dikholkar.png',
    then: 'Student founder with a product concept',
    now: 'built a physical MVP ready for market testing',
    fullThen: 'Chhavi had a concept but no product-development roadmap or business infrastructure.',
    fullNow: 'She collected feedback, sourced materials, worked with local suppliers, and built silk hat liners ready for testing.',
  },
  {
    id: 'simpleview',
    company: 'SimpleView',
    name: 'Sushant Jain',
    photo: 'FounderPics/SimpleView_Shushant_Jain.jpg',
    then: 'MVP-stage founder with unclear partner terms',
    now: 'closed two sales within 10 days of restructuring',
    fullThen: 'Sushant had a promising analytics product but unclear partnerships and an unfinished business model.',
    fullNow: 'After coaching, he onboarded a co-founder, hired sales support, and closed early sales quickly.',
  },
  {
    id: 'synoris',
    company: 'Synoris',
    name: 'Inderjeet Singh',
    photo: 'FounderPics/Synoris_Inderjeet_Singh.jpg',
    then: 'Product-heavy seller entering the Canadian market',
    now: 'shifted into relationship-first communication',
    fullThen: 'Inderjeet had deep logistics expertise but needed to adapt his sales style for the Canadian market.',
    fullNow: 'BNext supported incorporation, banking, go-to-market planning, grants, and a sharper pitch.',
  },
  {
    id: 'smartaura',
    company: 'SmartAura',
    name: 'Jai Inder Singh',
    photo: 'FounderPics/SmartAura_Jai_Inder.png',
    then: 'Working professional with a broad business ambition',
    now: 'ready to launch with a focused business plan',
    fullThen: 'Jai Inder wanted to build a company but needed clarity on customers, channels, and execution.',
    fullNow: 'He validated the idea, narrowed the audience, built marketing assets, and prepared to launch.',
  },
  {
    id: 'officeflow',
    company: 'OfficeFlow',
    name: 'Daljinder Singh',
    photo: 'FounderPics/OfficeFlow_Daljinder_Singh.png',
    then: 'Employee leaving a job to pursue entrepreneurship',
    now: 'running a revenue-generating business from BHive',
    fullThen: 'Daljinder left his job but lacked clarity on starting, contracts, client communication, and go-to-market strategy.',
    fullNow: 'He launched a dental marketing business in Brampton and moved from employee to employer.',
  },
  {
    id: 'nativchefs',
    company: 'Nativ Chefs',
    name: 'Leena Dixit',
    photo: 'FounderPics/NativChefs_Leena_Dixit.png',
    then: 'Founder bringing a proven model into Canadian regulations',
    now: 'pivoted into a compliant Brampton launch plan',
    fullThen: 'Leena had validated her model elsewhere, but Ontario food regulations made the original approach unworkable.',
    fullNow: 'BNext helped her understand regulations, connect with food incubators, and build a compliant path to launch.',
  },
  {
    id: 'treepz',
    company: 'Treepz',
    name: 'Onyeka Akumah',
    photo: 'FounderPics/Treepz_Onyeka_Akumah.png',
    photoPosition: 'center 62%',
    then: 'African mobility company entering North America',
    now: 'now has Brampton HQ + $500K project',
    fullThen: 'Treepz had international experience but needed Canadian market presence, partnerships, and government relationships.',
    fullNow: 'Treepz launched its North American headquarters in Brampton and secured a $500,000 project.',
  },
  {
    id: 'milesmate',
    company: 'Milesmate',
    name: 'Vikash Kumar',
    photo: 'FounderPics/Milesmate_Vikash_Verma.png',
    then: 'Early-stage MVP seeking international traction',
    now: 'secured US and Mexico clients with recurring revenue',
    fullThen: 'Milesmate had a live product but needed a scalable sales motion and international traction.',
    fullNow: 'The company secured international clients and reached early monthly recurring revenue.',
  },
  {
    id: 'oxana',
    company: 'Oxana Technologies',
    name: 'Frederick Elum',
    photo: 'FounderPics/OxanaTechnologies_Frederick_Elum.jpeg',
    then: 'First-time entrepreneur developing an MVP',
    now: 'onboarded major clients and global partnerships',
    fullThen: 'Frederick had no prior entrepreneurial experience, no refined pitch, and no clear path to market.',
    fullNow: 'Oxana built partnerships, sharpened its pitch, and onboarded major corporate clients.',
  },
];

export const shortFounderStories = ['dacasto', 'treepz', 'enabled-talent'].map((id) =>
  founderStories.find((story) => story.id === id)
);

export const modelPillars = [
  'high touch mentorship',
  'settlement and family support',
  'ecosystem access',
  'experienced operators',
  'localized business connections',
];

export const pilotProofs = [
  'Global entrepreneurial talent will choose Brampton when intentional support exists',
  'Early stage support can accelerate business creation and local economic participation',
  'Strong founder ecosystems require infrastructure, not just programming',
  'Continued momentum creates long term regional innovation capacity',
];

export const futureFocusAreas = [
  'scaling founder recruitment',
  'alumni retention',
  'sector specialization',
  'employer and commercialization partnerships',
];
